(define custom-activate-default-im-name? #t)
(define custom-preserved-default-im-name 'byeoru)
(define default-im-name 'byeoru)
(define enabled-im-list '(byeoru anthy-utf8 py))
(define enable-im-switch? #t)
(define switch-im-key '("<Control> "))
(define switch-im-key? (make-key-predicate '("<Control> ")))
(define switch-im-skip-direct-im? #t)
(define enable-im-toggle? #f)
(define toggle-im-key '("<Meta> "))
(define toggle-im-key? (make-key-predicate '("<Meta> ")))
(define toggle-im-alt-im 'direct)
(define uim-color 'uim-color-uim)
(define candidate-window-style 'vertical)
(define candidate-window-position 'caret)
(define enable-lazy-loading? #f)
(define bridge-show-input-state? #f)
(define bridge-show-with? 'time)
(define bridge-show-input-state-time-length 3)
